# Generated by Django 5.2.7 on 2025-10-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('skill_level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('address', models.TextField()),
                ('education_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='job_applications.educationhistory')),
                ('job_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='job_applications.job')),
                ('skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='job_applications.skill')),
            ],
        ),
    ]
