# Generated by Django 5.2.7 on 2025-10-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_remove_resume_education_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='job_applications.resume'),
        ),
    ]
